name: location_platform_interface
description: A common platform interface for the location plugin.
version: 2.3.0
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  plugin_platform_interface: any

dev_dependencies:
  async: any
  build_runner: any
  flutter_test:
    sdk: flutter
  mockito: any
